### ISSUE TITLE
Add CloudStack qcow2 templates to autobuild with the other images

### ISSUE THREAD

**Issue by maxdrib** [aws/eks-anywhere-build-tooling#1028]
**What would you like to be added**:
Enable CloudStack qcow2 image builder to run automatically alongside the other templates that are being built for VSphere

**Why is this needed**:
We recently encountered an issue where development and testing was being done against an outdated CloudStack qcow2 template which resulted in wasted time spent debugging and troubleshooting. The current process for building CloudStack qcow2 templates is manual and it's easy to make a mistake so we should automate it

**Comment by abhay-krishna** [comment]
Done
