### ISSUE TITLE
EKSA CAPI Image builder failed to build an image after pulling latest commits.

### ISSUE THREAD

**Issue by mdhavali** [aws/eks-anywhere-build-tooling#1048]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by abhay-krishna** [comment]
https://github.com/aws/eks-anywhere-build-tooling/pull/1047

Above PR should fix the build.

**Comment by mdhavali** [comment]
Thanks Abhay!

Madhura Dhavalikar
Sr. Technical Program Manager- Customer Engineering
AWS Professional Services

419.889.8016 - mobile


[signature_915940260]<http://www.aws.amazon.com/>[signature_463054155]


From: Abhay Krishna ***@***.***>
Reply-To: aws/eks-anywhere-build-tooling ***@***.***>
Date: Tuesday, July 12, 2022 at 11:24 AM
To: aws/eks-anywhere-build-tooling ***@***.***>
Cc: "Dhavalikar, Madhura" ***@***.***>, Author ***@***.***>
Subject: Re: [aws/eks-anywhere-build-tooling] EKSA CAPI Image builder failed to build an image after pulling latest commits. (Issue #1048)


#1047<https://github.com/aws/eks-anywhere-build-tooling/pull/1047>

Above PR should fix the build.
