### ISSUE TITLE
Makefile error: setup-packer-configs-ami

### ISSUE THREAD

**Issue by matthenslee** [aws/eks-anywhere-build-tooling#1697]
**What happened**: Trying to create a new Ubuntu 20.04 (w/ EKS-A 1.24) AMI with image-builder and encountered `[Makefile:207: setup-packer-configs-ami] Error 141`

**What you expected to happen**: An AMI to be produced successfully

**How to reproduce it (as minimally and precisely as possible)**: Follow the instructions in EKS-A documentation, get to the `image-builder` section and encounter this error. Others are noticing this as well. Can be reproduced using `image-builder build --os ubuntu --hypervisor ami --release-channel 1-24` with or without an AMI config and any release channel.

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: Any
- EKS Distro Release: Any 

Logs:
[image-builder-2.log](https://github.com/aws/eks-anywhere-build-tooling/files/10338307/image-builder-2.log)

**Comment by raykrueger** [comment]
@matthenslee this should be fixed now. Would you mind retesting?

**Comment by matthenslee** [comment]
Apologies for the delay @raykrueger - this fixed my issue. Thank you!
