### ISSUE TITLE
[bare metal][tinkerbell] multiple connected NICs cause cluster failure

### ISSUE THREAD

**Issue by jacobweinstock** [aws/eks-anywhere-build-tooling#2217]
**What happened**:
If multiple NICs are cabled and the first NIC that comes up in HookOS with an IP address is not the NIC specified in the hardware csv it will cause the cluster to fail. This is because we write static network configs and the way in which we determine which network interface to get DHCP info from is only determined based on the first interface that is found up and running with IP info. See this function here: https://github.com/aws/eks-anywhere-build-tooling/blob/f3caf094521ede3486b4a3116a1bf8c584ddf4a0/projects/tinkerbell/hub/patches/0003-Write-DHCP-offer-to-static-Netplan-file.patch#L214  

**What you expected to happen**:
We should make sure the MAC address is the expected one. This can be done by reading `/proc/cmdline` as it has the mac address in the `hw_addr=` arg.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by ph-armada** [comment]
Hi all - may I know if there is any update on this bug?

**Comment by jacobweinstock** [comment]
closed by https://github.com/aws/eks-anywhere-build-tooling/pull/2577
