### ISSUE TITLE
Modify sed command usage to make it compatible with macos

### ISSUE THREAD

**Issue by mrajashree** [aws/eks-anywhere-build-tooling#347]
Modify `sed` to use gnu-sed on macos as per [this comment](https://github.com/aws/eks-anywhere-build-tooling/pull/344#discussion_r788367861)

**Comment by TerryHowe** [comment]
There may be a couple places we use sed in the build scripts. I have `alias sed=gsed` but that shouldn't be a requirement for anyone using this stuff.

**Comment by mrajashree** [comment]
@TerryHowe I wasn't super clear in the issue description. I ran the script to build manifests locally on mac and the sed command needed some changes. Instead @abhay-krishna suggested adding in [this change](https://github.com/aws/eks-anywhere-build-tooling/pull/344#discussion_r788367861) which based on the os picks sed or gsed for the command. so anyone running this locally wouldn't have to do anything additional

**Comment by abhay-krishna** [comment]
We do this in both existing and new scripts (if necessary).
