### ISSUE TITLE
Unable to build RHEL9.2 based BareMetal node images using image-builder from RHEL 9.2 host

### ISSUE THREAD

**Issue by pdamianov** [aws/eks-anywhere-build-tooling#3691]
**What happened**: Following the Documentation https://anywhere.eks.amazonaws.com/docs/osmgmt/artifacts/#build-bare-metal-node-images, I tried to build node RHEL-based BareMetal node images using image-builder from RHEL 9.2 

**What you expected to happen**: Successfully build the images

**How to reproduce it (as minimally and precisely as possible)**: Follow the documentation and try to build RHEL-based node image from RHEL9.2-based admin host

**Anything else we need to know?**:
- run:
```sh 
image-builder build --os redhat --hypervisor baremetal --release-channel 1-29 --baremetal-config redhat/bm_rhel9.json --os-version 9 --force
```
![image](https://github.com/user-attachments/assets/38ac81ec-e6da-46d9-b2b9-176947ca9829)

- run: 
```sh
image-builder build --os redhat --hypervisor baremetal --release-channel 1-29 --baremetal-config redhat/bm_rhel9.json --os-version 9 --force --firmware efi
```
![image](https://github.com/user-attachments/assets/97be3140-89cd-4e20-ac34-9b1d99032a16)

- after two weeks of digging, I compiled qemu v6.20 and OVMF.fd from source and got some progress:
```sh 
image-builder build --os redhat --hypervisor baremetal --release-channel 1-29 --baremetal-config redhat/bm_rhel9.json --os-version 9 --force
```
![image](https://github.com/user-attachments/assets/386936e1-4459-4423-845b-352d7363f4e2)
- Question: Is it ok for ansible-playbook parameters to exist **ubuntu_repo=http://us.archive.ubuntu.com/ubuntu ubuntu_security_repo=http://security.ubuntu.com/ubuntu**
- more detailed log with --ansible-verbosity 6 flag:
![image](https://github.com/user-attachments/assets/096acc7d-8f00-4726-9584-daec9f2871cb)

**Environment**:
- EKS Anywhere Release: EKS A - 0.20.3
- EKS Distro Release: 1-29
- image-buider: 0.5.0
- host os RHEL 9.2

**Comment by abhay-krishna** [comment]
Thanks for reporting this issue! This issue has been fixed in https://github.com/aws/eks-anywhere/releases/tag/v0.20.7. Kindly download and use the corresponding image-builder CLI. Feel free to re-open this issue if the error persists.

**Comment by pdamianov** [comment]
I finally had the time to test the process with the fixed version and can confirm that only the part with **--firmware efi** was fixed.
Unfortunately, the other points stayed the same. The error again is: 
![image](https://github.com/user-attachments/assets/859d0647-9a27-47c4-bcb4-b18ff6824808)

Probably the error is related to the default OpenSSH behavior in RHEL9: https://www.redhat.com/en/blog/openssh-scp-deprecation-rhel-9-what-you-need-know

**Comment by abhay-krishna** [comment]
@pdamianov Yes, this indeed looks like the OpenSSH 9.0+ version incompatibility. OpenSSH 9.0 switched the default mode for `scp` from legacy mode to `sftp` mode, and the SSH proxy set up by the Packer Ansible plugin does not handle this correctly.

Can you try running `export ANSIBLE_SCP_EXTRA_ARGS="-O"` and then retry the image build? This option activates the legacy mode in `scp` for OpenSSH >= 9
```
-O Use the legacy SCP protocol for file transfers instead of the
   SFTP protocol. Forcing the use of the SCP protocol may be
   necessary for servers that do not implement SFTP, for
   backwards-compatibility for particular filename wildcard
   patterns and for expanding paths with a ‘~’ prefix for older
   SFTP servers.
```

**Comment by pdamianov** [comment]
@abhay-krishna Thanks a lot for the fast answer. RHEL9.4 comes with the OpenSSH 8.7
![{0B15DEF2-8A9A-4D05-B254-198439608A19}](https://github.com/user-attachments/assets/35eca6a0-b654-42ea-b37c-744629ebe81e)
Using the env variable:
`export ANSIBLE_SCP_EXTRA_ARGS="'-O'"`
did the trick.

I can confirm that I successfully built an RHEL9-based image on the RHEL9-based admin machine. To summarize what I did to succeed:
- built Qemu 6.2.0 from source and install it (installed missing dependencies):
`
tar xvJf qemu-6.2.0.tar.xz
cd qemu-6.2.0
./configure
make
make install
`
- built OVMF.fd from source (installed all missing dependencies): 
 `
git clone https://github.com/tianocore/edk2.git
cd edk2
git submodule update --init
make -C BaseTools
OvmfPkg/build.sh
sudo cp ./Build/OvmfX64/DEBUG_GCC5/FV/OVMF.fd /usr/share/OVMF
sudo ln -s /usr/share/OVMF/OVMF.fd /usr/local/share/qemu
` 
- added env variable: 
`export ANSIBLE_SCP_EXTRA_ARGS="'-O'"`

**Comment by abhay-krishna** [comment]
@pdamianov Awesome, glad to know that worked. We will add this workaround in the image-building documentation. Also thanks for sharing the steps to build the qemu binary and OVMF from source. Will be helpful to others who face this issue.

May I go ahead and close out this issue now that your image build failures have been resolved?
