### ISSUE TITLE
Ubuntu release not found when attempting to build Ubuntu-based Bare Metal node images using image-builder

### ISSUE THREAD

**Issue by jk-mob** [aws/eks-anywhere-build-tooling#3787]
**What happened**:
When following instructions [here](https://anywhere.eks.amazonaws.com/docs/osmgmt/artifacts/#build-bare-metal-node-images), at step 4, the command `image-builder build --os ubuntu --hypervisor baremetal --release-channel 1-30` failed to find the Ubuntu image, and thus did not complete successfully.

<img width="1246" alt="image" src="https://github.com/user-attachments/assets/5c8be3ce-e6ff-4b73-9193-292800d9da6c">

When browsing releases.ubuntu.com, it became clear that this version was no longer available.

**What you expected to happen**:
The Ubuntu image to be located and the build to complete successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the necessary steps for building an Ubuntu Bare Metal node image at the [guide](https://anywhere.eks.amazonaws.com/docs/osmgmt/artifacts/#building-node-images).
Run the aforementioned image-builder command at step 4 of the _building bare metal node images_ section.

**Anything else we need to know?**:
I was eventually able to build the image by providing the `--baremetal-config` flag and providing a valid link (I went with _https://releases.ubuntu.com/jammy/ubuntu-22.04.5-live-server-amd64.iso_) as the `iso_url`.

**Environment**:
- EKS Anywhere Release: v0.20.5
- EKS Distro Release: 1-30

**Comment by rahulbabu95** [comment]
Thanks for reporting this issue. The iso link comes from the upstream image-builder and this breaks whenever there's an ubuntu 22.04 is released as the previous released version becomes invalid then. The issue should be resolved with the image builder: https://github.com/aws/eks-anywhere-build-tooling/pull/3627 which will be included in our consequent release: v0.20.7. We will make a note to call this out on our docs about the workaround going forward.

**Comment by abhay-krishna** [comment]
Fixed with https://github.com/aws/eks-anywhere/releases/tag/v0.20.7. You can download and use the corresponding image-builder CLI to build images without this problem.

**Comment by Cajga** [comment]
@abhay-krishna , seems the fix did not make it to `v.0.20.7`. I just tried to build a new ubuntu image with the latest image-builder and got the same error message like @jk-mob:
```
$ EKSA_RELEASE_VERSION=$(curl -sL https://anywhere-assets.eks.amazonaws.com/releases/eks-a/manifest.yaml | yq ".spec.latestVersion")
$ echo $EKSA_RELEASE_VERSION
v0.20.7
$ cd /tmp
$ BUNDLE_MANIFEST_URL=$(curl -s https://anywhere-assets.eks.amazonaws.com/releases/eks-a/manifest.yaml | yq ".spec.releases[] | select(.version==\"$EKSA_RELEASE_VERSION\").bundleManifestUrl")
$ IMAGEBUILDER_TARBALL_URI=$(curl -s $BUNDLE_MANIFEST_URL | yq ".spec.versionsBundles[0].eksD.imagebuilder.uri")
$ curl -s $IMAGEBUILDER_TARBALL_URI | tar xz ./image-builder
$ sudo install -m 0755 ./image-builder /usr/local/bin/image-builder   
$ cd -
/home/image-builder
$ /usr/local/bin/image-builder version
v0.5.0
$ image-builder build --os ubuntu --os-version 22.04 --hypervisor baremetal --release-channel 1-30
Creating builder config
2024/10/14 08:17:45 Reading EKS-A Manifest file: https://anywhere-assets.eks.amazonaws.com/releases/eks-a/manifest.yaml
2024/10/14 08:17:46 No EKS-A release version provided, defaulting to EKS-A version configured at build time: v0.20.7
2024/10/14 08:17:46 Fetching git commit from bundle manifest: https://anywhere-assets.eks.amazonaws.com/releases/bundles/78/manifest.yaml
2024/10/14 08:17:47 Cloning eks-anywhere-build-tooling from https://github.com/aws/eks-anywhere-build-tooling.git...
.
.
.
qemu: output will be in this color.

==> qemu: Retrieving ISO
==> qemu: Trying https://releases.ubuntu.com/22.04.4/ubuntu-22.04.4-live-server-amd64.iso
==> qemu: Trying https://releases.ubuntu.com/22.04.4/ubuntu-22.04.4-live-server-amd64.iso?checksum=sha256%3A45f873de9f8cb637345d6e66a583762730bbea30277ef7b32c9c3bd6700a32b2
==> qemu: Download failed bad response code: 404
==> qemu: error downloading ISO: [bad response code: 404]
Build 'qemu' errored after 829 milliseconds 400 microseconds: error downloading ISO: [bad response code: 404]

==> Wait completed after 829 milliseconds 453 microseconds
```
