### ISSUE TITLE
Migrate to goharbor/harbor-scanner-trivy for Harbor Scanner Adapter for Trivy

### ISSUE THREAD

**Issue by abhay-krishna** [aws/eks-anywhere-build-tooling#4017]
The Harbor Scanner Adapter for Trivy project was being maintained in the [aquasecurity/harbor-scanner-trivy](https://github.com/aquasecurity/harbor-scanner-trivy) repository but that repository has been archived and is no longer being maintained. Future development of this project has been migrated to the [goharbor/harbor-scanner-trivy](https://github.com/goharbor/harbor-scanner-trivy) repository so we should change our build-tooling repo to use that instead.

**Comment by sp1999** [comment]
Packages and Build CDK changes for creating codepipeline, codebuild project and codecommit repo have been merged. Presubmit prow job and build tooling PRs have also been merged.
