### ISSUE TITLE
CodeBuild image link

### ISSUE THREAD

**Issue by tuxtof** [aws/eks-anywhere-build-tooling#607]
Where are the link of the CodeBuild raw image ???

![image](https://user-images.githubusercontent.com/180613/160228742-7b52fd30-9a46-41e9-ae64-2f2ed6a9c0c0.png)

**Comment by TerryHowe** [comment]
The raw images are for baremetal. I'm pretty sure they are qcow2 format but I haven't worked with that.

**Comment by tuxtof** [comment]
yes agree but where are they ??? , i see CodeBuid passing but i don't find any link

**Comment by abhay-krishna** [comment]
We don't put artifact links in this repository. But you can find the latest raw images at this location
```
RELEASE_BRANCH=1-21 #1-20, 1-21 or 1-22
EKSA_DEV_BUILD_BUCKET=https://projectbuildpipeline-857-pipelineoutputartifactsb-10ajmk30khe3f

wget $EKSA_DEV_BUILD_BUCKET.s3.amazonaws.com
/projects/kubernetes-sigs/image-builder/$RELEASE_BRANCH/raw/latest/ubuntu.gz
```

These are dev builds from `main`.

**Comment by abhay-krishna** [comment]
These Ubuntu images are Raw format, not `qcow2`. We are yet to release an official `qcow2` image for Ubuntu.

**Comment by tuxtof** [comment]
it is perfect @abhay-krishna , i would test
when did you think you will publish official qcow2 image for Ubuntu ?
